//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtaSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtaSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ActiveColor {
            get {
                return ResourceManager.GetString("ActiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string ActiveLabel {
            get {
                return ResourceManager.GetString("ActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoPAIDmWifIAFXmb6FhfaoNFRJvEu3zWjCYPUNtIU6rcruFx5RW6sIzJKGo0WP9N.
        /// </summary>
        public static string BingApiKey {
            get {
                return ResourceManager.GetString("BingApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Catalogs.
        /// </summary>
        public static string CatalogBaseIsoFolder {
            get {
                return ResourceManager.GetString("CatalogBaseIsoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da-DK.
        /// </summary>
        public static string CultureString {
            get {
                return ResourceManager.GetString("CultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://etilbudsavis.dk.
        /// </summary>
        public static string Eta_BaseUri {
            get {
                return ResourceManager.GetString("Eta_BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ExpiredColor {
            get {
                return ResourceManager.GetString("ExpiredColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udløbet.
        /// </summary>
        public static string ExpiredLabel {
            get {
                return ResourceManager.GetString("ExpiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommer snart.
        /// </summary>
        public static string InActiveLabel {
            get {
                return ResourceManager.GetString("InActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/listbg.png.
        /// </summary>
        public static string LoadingCatalogPageImageThumb {
            get {
                return ResourceManager.GetString("LoadingCatalogPageImageThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/_listbg450.png.
        /// </summary>
        public static string LoadingCatalogPageImageView {
            get {
                return ResourceManager.GetString("LoadingCatalogPageImageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/listbg.png.
        /// </summary>
        public static string LoadingCatalogPageImageZoom {
            get {
                return ResourceManager.GetString("LoadingCatalogPageImageZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string NotActiveColor {
            get {
                return ResourceManager.GetString("NotActiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fra.
        /// </summary>
        public static string RunFromLabel {
            get {
                return ResourceManager.GetString("RunFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to til.
        /// </summary>
        public static string RunTillLabel {
            get {
                return ResourceManager.GetString("RunTillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra i dag.
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra i morgen.
        /// </summary>
        public static string TomorrowLabel {
            get {
                return ResourceManager.GetString("TomorrowLabel", resourceCulture);
            }
        }
    }
}
