//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtaSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtaSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Catalogs.
        /// </summary>
        public static string CatalogBaseIsoFolder {
            get {
                return ResourceManager.GetString("CatalogBaseIsoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c2a0bb532723548de341506555749d8f.
        /// </summary>
        public static string Eta_API_Key {
            get {
                return ResourceManager.GetString("Eta_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80366342196ea27b14632a5b4e764b9d.
        /// </summary>
        public static string Eta_API_Secret {
            get {
                return ResourceManager.GetString("Eta_API_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://etilbudsavis.dk.
        /// </summary>
        public static string Eta_BaseUri {
            get {
                return ResourceManager.GetString("Eta_BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/listbg.png.
        /// </summary>
        public static string LoadingCatalogPageImageThumb {
            get {
                return ResourceManager.GetString("LoadingCatalogPageImageThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/listbg.png.
        /// </summary>
        public static string LoadingCatalogPageImageView {
            get {
                return ResourceManager.GetString("LoadingCatalogPageImageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/listbg.png.
        /// </summary>
        public static string LoadingCatalogPageImageZoom {
            get {
                return ResourceManager.GetString("LoadingCatalogPageImageZoom", resourceCulture);
            }
        }
    }
}
