//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtaSampleApp.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtaSampleApp.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://etilbudsavis.dk/about/.
        /// </summary>
        public static string AboutUrl {
            get {
                return ResourceManager.GetString("AboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillad brug af GPS.
        /// </summary>
        public static string AllowGPSHeader {
            get {
                return ResourceManager.GetString("AllowGPSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to om.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indstillinger.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opdater.
        /// </summary>
        public static string AppBarUpdate {
            get {
                return ResourceManager.GetString("AppBarUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuller.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aviser.
        /// </summary>
        public static string CatalogHeader {
            get {
                return ResourceManager.GetString("CatalogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortsæt.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        public static string DistancePrefixKilometers {
            get {
                return ResourceManager.GetString("DistancePrefixKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string DistancePrefixMeters {
            get {
                return ResourceManager.GetString("DistancePrefixMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF7b9119.
        /// </summary>
        public static string EtaSignatureColor {
            get {
                return ResourceManager.GetString("EtaSignatureColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis indenfor .
        /// </summary>
        public static string EtaSliderControlText {
            get {
                return ResourceManager.GetString("EtaSliderControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ingen internet forbindelse ... og eTilbudsavis appen virker ikke uden!.
        /// </summary>
        public static string NoNetworkDescription {
            get {
                return ResourceManager.GetString("NoNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups!.
        /// </summary>
        public static string NoNetworkHeader {
            get {
                return ResourceManager.GetString("NoNetworkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tilbud.
        /// </summary>
        public static string OfferHeader {
            get {
                return ResourceManager.GetString("OfferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åben netværksopsætning.
        /// </summary>
        public static string OpenNetworkSettingsLabel {
            get {
                return ResourceManager.GetString("OpenNetworkSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post nr..
        /// </summary>
        public static string PostalNumberHeader {
            get {
                return ResourceManager.GetString("PostalNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din aktuelle position bruges til at forbedre søgningen og vise mest relevante tilbud. Dine lokationsdata deles ikke med 3. part og du forbliver anonym..
        /// </summary>
        public static string PrivacyPolicyLocationDataText {
            get {
                return ResourceManager.GetString("PrivacyPolicyLocationDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://etilbudsavis.dk/privacy/.
        /// </summary>
        public static string PrivacyPolicyLocationDataUri {
            get {
                return ResourceManager.GetString("PrivacyPolicyLocationDataUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Læs mere her..
        /// </summary>
        public static string PrivacyPolicyLocationDataUriText {
            get {
                return ResourceManager.GetString("PrivacyPolicyLocationDataUriText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to søg.
        /// </summary>
        public static string SearchHeader {
            get {
                return ResourceManager.GetString("SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indstillinger.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henter....
        /// </summary>
        public static string SplashScreenLoadingText {
            get {
                return ResourceManager.GetString("SplashScreenLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1988.
        /// </summary>
        public static string SplashScreenPopupLoadtime {
            get {
                return ResourceManager.GetString("SplashScreenPopupLoadtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Windows Phone.
        /// </summary>
        public static string SplashScreenSubHeaderText {
            get {
                return ResourceManager.GetString("SplashScreenSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butikker.
        /// </summary>
        public static string StoreHeader {
            get {
                return ResourceManager.GetString("StoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eTilbudsavis.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
